steps:
  # Build the Docker image with VITE_API_URL baked in at build time
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'VITE_API_URL=https://the-nest-api-114675580879.australia-southeast1.run.app/api'
      - '--build-arg'
      - 'VITE_FIREBASE_API_KEY=AIzaSyAPT1TDq0ObzJmFxE8xhGdQv1gecvyipHQ'
      - '--build-arg'
      - 'VITE_FIREBASE_AUTH_DOMAIN=bill-sandpit.firebaseapp.com'
      - '--build-arg'
      - 'VITE_FIREBASE_PROJECT_ID=bill-sandpit'
      - '--build-arg'
      - 'VITE_FIREBASE_STORAGE_BUCKET=bill-sandpit.firebasestorage.app'
      - '--build-arg'
      - 'VITE_FIREBASE_MESSAGING_SENDER_ID=114675580879'
      - '--build-arg'
      - 'VITE_FIREBASE_APP_ID=1:114675580879:web:9e66b8eea6da493fbadcba'
      - '--build-arg'
      - 'VITE_FIREBASE_MEASUREMENT_ID=G-QKJ8JJF9JW'
      - '--no-cache'
      - '-t'
      - 'gcr.io/$PROJECT_ID/the-nest-frontend:latest'
      - '.'

  # Push the image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/the-nest-frontend:latest']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'the-nest-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/the-nest-frontend:latest'
      - '--region'
      - 'australia-southeast1'
      - '--allow-unauthenticated'
      - '--port'
      - '80'

images:
  - 'gcr.io/$PROJECT_ID/the-nest-frontend:latest'
